# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: Joseph Warren
# Generated on: 5/21/2019

@{
    RootModule        = 'OfflineWSUS.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = 'c5db6b47-fe66-4f43-a112-451f492ac297'
    Author            = 'Joseph Warren'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Joseph Warren. All rights reserved.'
    Description       = ''
    FunctionsToExport = '*'
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    RequiredModules   = @("PoshWSUS", "PSFramework")
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            Tags       = @("WSUS")
            LicenseUri = 'https://github.com/luzkenin/OfflineWSUS/blob/master/LICENSE'
            ProjectUri = 'https://github.com/luzkenin/OfflineWSUS'
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

